#!/bin/bash
# Meridian — Machine Setup Script
# Run this once on each machine to install the CLI, Syncthing, and session hook.
#
# Usage:
#   cd /path/to/meridian
#   bash scripts/setup-machine.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

VM_IP="178.156.209.202"
VM_USER="root"
VM_SYNCTHING_DEVICE_ID="DI5EKMW-F62MMYX-OFVPLP6-JGOWUVG-YVHJODP-QWTTN7X-2MU724L-NRB44A3"
COOLIFY_KEY_UUID="qo40kgg4wggkso44w44gkc8k"
COOLIFY_SERVER_UUID="as0gwg4ooow4w0sc0cccosk4"

echo "============================================"
echo "  Meridian — Machine Setup"
echo "============================================"
echo ""

# ---- 1. Collect credentials ----

read -rp "Meridian receiver URL [https://meridian.markahope.com]: " RECEIVER_URL
RECEIVER_URL="${RECEIVER_URL:-https://meridian.markahope.com}"
read -rp "Meridian receiver token: " RECEIVER_TOKEN

if [ -z "$RECEIVER_TOKEN" ]; then
    echo "Error: token is required."
    exit 1
fi

read -rp "Coolify API token (from app.coolify.io > Keys & Tokens): " COOLIFY_TOKEN

if [ -z "$COOLIFY_TOKEN" ]; then
    echo "Error: Coolify token is required for VM access."
    exit 1
fi

# Strip trailing slash
RECEIVER_URL="${RECEIVER_URL%/}"

# ---- 2. Create ~/.meridian/ config and credentials ----

MERIDIAN_DIR="$HOME/.meridian"
mkdir -p "$MERIDIAN_DIR"

cat > "$MERIDIAN_DIR/config.yaml" <<YAML
# Meridian CLI config — generated by setup-machine.sh
receiver_url: ${RECEIVER_URL}
token: ${RECEIVER_TOKEN}
YAML
echo "[ok] Created $MERIDIAN_DIR/config.yaml"

cat > "$MERIDIAN_DIR/.env" <<ENV
# Meridian infrastructure credentials — generated by setup-machine.sh
# This file is outside the repo — never commit these values

# Hetzner VM
VM_IP=${VM_IP}
VM_USER=${VM_USER}

# Coolify API
COOLIFY_BASE_URL=https://app.coolify.io/api/v1
COOLIFY_API_TOKEN=${COOLIFY_TOKEN}
COOLIFY_SERVER_UUID=${COOLIFY_SERVER_UUID}

# Syncthing (on VM) — populated after SSH is established
SYNCTHING_API_KEY=
SYNCTHING_CONFIG=/root/.config/syncthing/config.xml

# VM Syncthing Device ID
VM_SYNCTHING_DEVICE_ID=${VM_SYNCTHING_DEVICE_ID}
ENV
echo "[ok] Created $MERIDIAN_DIR/.env"

# ---- 3. Fetch Coolify SSH key ----

echo ""
echo "Fetching Coolify SSH key for VM access..."

curl -s -H "Authorization: Bearer ${COOLIFY_TOKEN}" -H "Accept: application/json" \
  "https://app.coolify.io/api/v1/security/keys/${COOLIFY_KEY_UUID}" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['private_key'])" \
  > "$MERIDIAN_DIR/coolify_rsa"

chmod 600 "$MERIDIAN_DIR/coolify_rsa"

# Verify SSH works
if ssh -i "$MERIDIAN_DIR/coolify_rsa" -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o BatchMode=yes \
   ${VM_USER}@${VM_IP} "echo ok" &>/dev/null; then
    echo "[ok] SSH to VM verified"
    SSH_CMD="ssh -i $MERIDIAN_DIR/coolify_rsa -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP}"
else
    echo "[error] Cannot SSH to VM. Check Coolify token and try again."
    exit 1
fi

# ---- 4. Add local SSH key to VM ----

if [ -f "$HOME/.ssh/id_ed25519.pub" ]; then
    LOCAL_PUBKEY=$(cat "$HOME/.ssh/id_ed25519.pub")
    $SSH_CMD "grep -qF '$(echo $LOCAL_PUBKEY | awk '{print $2}')' ~/.ssh/authorized_keys 2>/dev/null || echo '$LOCAL_PUBKEY' >> ~/.ssh/authorized_keys"
    echo "[ok] Local SSH key added to VM authorized_keys"
elif [ -f "$HOME/.ssh/id_rsa.pub" ]; then
    LOCAL_PUBKEY=$(cat "$HOME/.ssh/id_rsa.pub")
    $SSH_CMD "grep -qF '$(echo $LOCAL_PUBKEY | awk '{print $2}')' ~/.ssh/authorized_keys 2>/dev/null || echo '$LOCAL_PUBKEY' >> ~/.ssh/authorized_keys"
    echo "[ok] Local SSH key added to VM authorized_keys"
else
    echo "[skip] No local SSH key found — use coolify_rsa for SSH access"
fi

# ---- 5. Get Syncthing API key from VM ----

ST_API_KEY=$($SSH_CMD "grep -oP '<apikey>\K[^<]+' /root/.config/syncthing/config.xml" 2>/dev/null || echo "")
if [ -n "$ST_API_KEY" ]; then
    sed -i "s/^SYNCTHING_API_KEY=.*/SYNCTHING_API_KEY=${ST_API_KEY}/" "$MERIDIAN_DIR/.env"
    echo "[ok] Syncthing API key retrieved and saved"
fi

# ---- 6. Install Syncthing ----

echo ""
if command -v syncthing &>/dev/null; then
    echo "[skip] Syncthing already installed"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" ]]; then
    echo "Installing Syncthing via winget..."
    winget install Syncthing.Syncthing --accept-source-agreements --accept-package-agreements 2>/dev/null || true

    # Find and copy to accessible location
    ST_EXE=$(find "$LOCALAPPDATA/Microsoft/WinGet/Packages" -name "syncthing.exe" 2>/dev/null | head -1)
    if [ -n "$ST_EXE" ]; then
        cp "$ST_EXE" "$HOME/syncthing.exe"
        echo "[ok] Syncthing installed to ~/syncthing.exe"

        # Create startup shortcut
        powershell.exe -NoProfile -Command '
            $WshShell = New-Object -ComObject WScript.Shell
            $Shortcut = $WshShell.CreateShortcut("$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\Syncthing.lnk")
            $Shortcut.TargetPath = "$env:USERPROFILE\syncthing.exe"
            $Shortcut.WindowStyle = 7
            $Shortcut.Save()
        ' 2>/dev/null && echo "[ok] Syncthing startup shortcut created"

        # Start it now
        powershell.exe -NoProfile -Command "Start-Process '$HOME\syncthing.exe' -WindowStyle Hidden" 2>/dev/null
        echo "[ok] Syncthing started (background)"
    else
        echo "[warn] winget installed Syncthing but exe not found — install manually"
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    brew install syncthing
    brew services start syncthing
    echo "[ok] Syncthing installed and started"
else
    echo "[warn] Install Syncthing manually for this OS"
fi

# ---- 7. Pair Syncthing with VM ----

echo ""
echo "Pairing Syncthing with VM..."

# Wait for local Syncthing to be ready
for i in {1..10}; do
    LOCAL_DEVICE_ID=$(curl -s http://localhost:8384/rest/system/status 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('myID',''))" 2>/dev/null || echo "")
    if [ -n "$LOCAL_DEVICE_ID" ]; then
        break
    fi
    sleep 2
done

if [ -z "$LOCAL_DEVICE_ID" ]; then
    echo "[warn] Local Syncthing not responding — pair manually after starting it."
    echo "       VM device ID: ${VM_SYNCTHING_DEVICE_ID}"
else
    MACHINE_NAME=$(hostname)
    $SSH_CMD "syncthing cli config devices add --device-id=${LOCAL_DEVICE_ID} --name=${MACHINE_NAME}" 2>/dev/null || true
    $SSH_CMD "syncthing cli config folders meridian devices add --device-id=${LOCAL_DEVICE_ID}" 2>/dev/null || true
    $SSH_CMD "systemctl restart syncthing" 2>/dev/null || true
    echo "[ok] VM paired with this machine (device: ${MACHINE_NAME})"
    echo ""
    echo "  >>> Open http://localhost:8384 in your browser"
    echo "  >>> Add remote device: ${VM_SYNCTHING_DEVICE_ID}"
    echo "  >>> Accept the 'meridian' folder when prompted"
    if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" ]]; then
        echo "  >>> Set folder path to: C:\\Users\\$(whoami)\\Meridian"
    else
        echo "  >>> Set folder path to: ~/Meridian"
    fi
fi

# ---- 8. Install the CLI ----

echo ""
echo "Installing meridian CLI..."
pip install -e "$PROJECT_DIR/cli" --quiet
echo "[ok] Installed meridian CLI (run 'meridian status' to test)"

# ---- 9. Install Claude Code post-session hook ----

HOOKS_DIR="$HOME/.claude/hooks"
SETTINGS_FILE="$HOME/.claude/settings.json"

mkdir -p "$HOOKS_DIR"

cp "$PROJECT_DIR/scripts/hooks/post-session.sh" "$HOOKS_DIR/post-session.sh"
chmod +x "$HOOKS_DIR/post-session.sh"
echo "[ok] Copied post-session.sh to $HOOKS_DIR/"

# ---- 10. Register hook in ~/.claude/settings.json ----

HOOK_ENTRY='{
  "matcher": "",
  "hooks": [
    {
      "type": "command",
      "command": "~/.claude/hooks/post-session.sh"
    }
  ]
}'

if [ -f "$SETTINGS_FILE" ]; then
    if echo "$(cat "$SETTINGS_FILE")" | grep -q "post-session.sh"; then
        echo "[skip] Hook already registered in settings.json"
    else
        if command -v jq &>/dev/null; then
            cat "$SETTINGS_FILE" | jq --argjson entry "$HOOK_ENTRY" '
                .hooks //= {} |
                .hooks.Stop //= [] |
                .hooks.Stop += [$entry]
            ' > "$SETTINGS_FILE.tmp" && mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"
            echo "[ok] Merged hook into existing settings.json"
        else
            echo "[error] jq is required to merge settings.json safely."
            echo "        Install jq and re-run, or add the hook manually."
        fi
    fi
else
    mkdir -p "$(dirname "$SETTINGS_FILE")"
    cat > "$SETTINGS_FILE" <<SETTINGS
{
  "hooks": {
    "PostToolUse": [],
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/post-session.sh"
          }
        ]
      }
    ]
  }
}
SETTINGS
    echo "[ok] Created settings.json with hook registration"
fi

# ---- 11. Export env vars to shell profile ----

if [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
    SHELL_RC="$HOME/.bashrc"
else
    SHELL_RC="$HOME/.bashrc"
fi

if ! grep -q "MERIDIAN_RECEIVER_URL" "$SHELL_RC" 2>/dev/null; then
    cat >> "$SHELL_RC" <<EXPORTS

# Meridian — receiver config (added by setup-machine.sh)
export MERIDIAN_RECEIVER_URL="${RECEIVER_URL}"
export MERIDIAN_RECEIVER_TOKEN="${RECEIVER_TOKEN}"
EXPORTS
    echo "[ok] Added env vars to $SHELL_RC"
else
    echo "[skip] Env vars already in $SHELL_RC — update manually if needed"
fi

export MERIDIAN_RECEIVER_URL="$RECEIVER_URL"
export MERIDIAN_RECEIVER_TOKEN="$RECEIVER_TOKEN"

# ---- 12. Verify ----

echo ""
echo "Verifying installation..."
echo ""

if command -v meridian &>/dev/null; then
    meridian status && echo "" && echo "[ok] Receiver is reachable" || {
        echo ""
        echo "[warn] Receiver not reachable — is it deployed on Coolify yet?"
    }
else
    echo "[warn] 'meridian' command not found in PATH."
    echo "       You may need to restart your shell or run: source $SHELL_RC"
fi

echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "  CLI:         meridian ask 'your question'"
echo "  SSH to VM:   ssh root@${VM_IP}"
echo "  Hook:        $HOOKS_DIR/post-session.sh"
echo "  Config:      $MERIDIAN_DIR/config.yaml"
echo "  Credentials: $MERIDIAN_DIR/.env"
echo "  SSH key:     $MERIDIAN_DIR/coolify_rsa"
echo ""
echo "  Syncthing:   http://localhost:8384"
echo "  Obsidian:    Open the Meridian folder as a vault"
echo ""
