#!/bin/bash
# Meridian — Machine Setup Script
# Run this once on each machine to install the CLI and session hook.
#
# Usage:
#   cd /path/to/meridian
#   bash scripts/setup-machine.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "============================================"
echo "  Meridian — Machine Setup"
echo "============================================"
echo ""

# ---- 1. Collect credentials ----

read -rp "Meridian receiver URL [https://meridian.markahope.com]: " RECEIVER_URL
RECEIVER_URL="${RECEIVER_URL:-https://meridian.markahope.com}"
read -rp "Meridian receiver token: " RECEIVER_TOKEN

if [ -z "$RECEIVER_TOKEN" ]; then
    echo "Error: token is required."
    exit 1
fi

# Strip trailing slash
RECEIVER_URL="${RECEIVER_URL%/}"

# ---- 2. Create ~/.meridian/config.yaml ----

MERIDIAN_DIR="$HOME/.meridian"
mkdir -p "$MERIDIAN_DIR"

cat > "$MERIDIAN_DIR/config.yaml" <<YAML
# Meridian CLI config — generated by setup-machine.sh
receiver_url: ${RECEIVER_URL}
token: ${RECEIVER_TOKEN}
YAML

echo "[ok] Created $MERIDIAN_DIR/config.yaml"

# ---- 3. Install the CLI ----

echo ""
echo "Installing meridian CLI..."
pip install -e "$PROJECT_DIR/cli" --quiet
echo "[ok] Installed meridian CLI (run 'meridian status' to test)"

# ---- 4. Install Claude Code post-session hook ----

HOOKS_DIR="$HOME/.claude/hooks"
SETTINGS_FILE="$HOME/.claude/settings.json"

mkdir -p "$HOOKS_DIR"

cp "$PROJECT_DIR/scripts/hooks/post-session.sh" "$HOOKS_DIR/post-session.sh"
chmod +x "$HOOKS_DIR/post-session.sh"
echo "[ok] Copied post-session.sh to $HOOKS_DIR/"

# ---- 5. Register hook in ~/.claude/settings.json ----

# The Stop hook entry we need to add
HOOK_ENTRY='{
  "matcher": "",
  "hooks": [
    {
      "type": "command",
      "command": "~/.claude/hooks/post-session.sh"
    }
  ]
}'

if [ -f "$SETTINGS_FILE" ]; then
    # settings.json exists — merge without overwriting other settings
    EXISTING=$(cat "$SETTINGS_FILE")

    # Check if hook is already registered
    if echo "$EXISTING" | grep -q "post-session.sh"; then
        echo "[skip] Hook already registered in settings.json"
    else
        # Use jq to merge: add Stop hook while preserving everything else
        if command -v jq &>/dev/null; then
            echo "$EXISTING" | jq --argjson entry "$HOOK_ENTRY" '
                # Ensure hooks object exists
                .hooks //= {} |
                # Ensure Stop array exists
                .hooks.Stop //= [] |
                # Append our hook entry
                .hooks.Stop += [$entry]
            ' > "$SETTINGS_FILE.tmp" && mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"
            echo "[ok] Merged hook into existing settings.json"
        else
            echo "[error] jq is required to merge settings.json safely."
            echo "        Install jq and re-run, or add the hook manually."
            echo "        Hook entry to add to .hooks.Stop[]:"
            echo "$HOOK_ENTRY"
            exit 1
        fi
    fi
else
    # settings.json doesn't exist — create it
    mkdir -p "$(dirname "$SETTINGS_FILE")"
    cat > "$SETTINGS_FILE" <<SETTINGS
{
  "hooks": {
    "PostToolUse": [],
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/post-session.sh"
          }
        ]
      }
    ]
  }
}
SETTINGS
    echo "[ok] Created settings.json with hook registration"
fi

# Verify hook appears in settings.json
if grep -q "post-session.sh" "$SETTINGS_FILE"; then
    echo "[ok] Confirmed: hook registered in $SETTINGS_FILE"
else
    echo "[error] Hook not found in settings.json after write — check manually"
    exit 1
fi

# ---- 6. Export env vars to shell profile ----

# Detect shell
if [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
    SHELL_RC="$HOME/.bashrc"
else
    SHELL_RC="$HOME/.bashrc"
fi

# Check if already exported
if ! grep -q "MERIDIAN_RECEIVER_URL" "$SHELL_RC" 2>/dev/null; then
    cat >> "$SHELL_RC" <<EXPORTS

# Meridian — receiver config (added by setup-machine.sh)
export MERIDIAN_RECEIVER_URL="${RECEIVER_URL}"
export MERIDIAN_RECEIVER_TOKEN="${RECEIVER_TOKEN}"
EXPORTS
    echo "[ok] Added env vars to $SHELL_RC"
else
    echo "[skip] Env vars already in $SHELL_RC — update manually if needed"
fi

# Export for current session
export MERIDIAN_RECEIVER_URL="$RECEIVER_URL"
export MERIDIAN_RECEIVER_TOKEN="$RECEIVER_TOKEN"

# ---- 7. Verify ----

echo ""
echo "Verifying installation..."
echo ""

if command -v meridian &>/dev/null; then
    meridian status && echo "" && echo "[ok] Receiver is reachable" || {
        echo ""
        echo "[warn] Receiver not reachable — is it deployed on Coolify yet?"
        echo "       The CLI is installed correctly. Deploy the receiver first,"
        echo "       then run 'meridian status' to confirm."
    }
else
    echo "[warn] 'meridian' command not found in PATH."
    echo "       You may need to restart your shell or run: source $SHELL_RC"
fi

echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "  CLI:      meridian ask 'your question'"
echo "  Hook:     $HOOKS_DIR/post-session.sh"
echo "  Settings: $SETTINGS_FILE"
echo "  Config:   $MERIDIAN_DIR/config.yaml"
echo ""
